components_manager:
    coro_pool:
        initial_size: 50
        max_size: 100
 
    task_processors:                  # Task processor is an executor for coroutine tasks
 
        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: 2
            thread_name: main-worker  # OS will show the threads of this task processor with 'main-worker' prefix.
 
        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            thread_name: fs-worker
            worker_threads: 2
 
    default_task_processor: main-task-processor
 
    components:                       # Configuring components that were registered via component_list
        http-client:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor
        server:
            listener:                 # configuring the main listening socket...
                port: 8080            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        tracer:
            service-name: service_template
 
        dynamic-config:                      # Dynamic config storage options, do nothing
            fs-cache-path: ''

        dynamic-config-fallbacks:            # Load options from file and push them into the dynamic config storage.
            fallback-path: /app/dynamic_config.json
 
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
        handler-infra-version:
            path: /check-infra-version
            method: POST
            task_processor: main-task-processor
